// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/12/2025, 00:40:49
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/User/TOP-Website/TOP-Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/plugins/**/*.{js,ts,mjs}","C:/Users/User/TOP-Website/TOP-Website/composables/**/*.{js,ts,mjs}","C:/Users/User/TOP-Website/TOP-Website/utils/**/*.{js,ts,mjs}","C:/Users/User/TOP-Website/TOP-Website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/TOP-Website/TOP-Website/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;